dist: trusty
language: c
os: linux
notifications:
  email: false

before_install:
  - sudo apt install libsdl2-dev libsdl2-2.0-0 -y
  - pip install --user cpp-coveralls

script:
  - ./cmocka-setup.sh 

after_success:
  - coveralls -e cmocka-1.1.2/ -e cmocka-build/ -e include/ -e tests --gcov-options '\-lp'
