dist: trusty
language: c
os: linux
notifications:
  email: false

before_install:
  - pip install --user cpp-coveralls

jobs:
  include:
    - stage: travis testing
      script: ./cmocka-setup.sh 

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
